# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FireBaseTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Core'
pod 'Firebase/Crashlytics'
pod 'Firebase/Database'
# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
  # Pods for FireBaseTest

end
